-- Creación de las tablas principales

CREATE TABLE Afiliados (
    id_afiliado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    telefono VARCHAR2(20),
    direccion VARCHAR2(255),
    id_afiliado_superior NUMBER,  -- FK a la misma tabla
    fecha_afiliacion DATE DEFAULT SYSDATE,
    nivel NUMBER DEFAULT 1,
    CONSTRAINT fk_afiliado_superior FOREIGN KEY (id_afiliado_superior) REFERENCES Afiliados(id_afiliado) ON DELETE SET NULL
);

CREATE TABLE Productos (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    precio NUMBER(10, 2) NOT NULL,
    stock NUMBER DEFAULT 0
);

CREATE TABLE Ventas (
    id_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_afiliado NUMBER NOT NULL,  -- FK a Afiliados
    fecha_venta DATE DEFAULT SYSDATE,
    total_venta NUMBER(10, 2),
    estado VARCHAR2(50) DEFAULT 'PENDIENTE',
    CONSTRAINT fk_afiliado_venta FOREIGN KEY (id_afiliado) REFERENCES Afiliados(id_afiliado) ON DELETE CASCADE
);

CREATE TABLE Promociones (
    id_promocion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(255) NOT NULL,
    descuento_porcentaje NUMBER(3, 2),
    fecha_inicio DATE,
    fecha_fin DATE
);

CREATE TABLE Despachos (
    id_despacho NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta NUMBER NOT NULL,  -- FK a Ventas
    fecha_despacho DATE DEFAULT SYSDATE,
    estado VARCHAR2(50) DEFAULT 'EN PROCESO',
    direccion_envio VARCHAR2(255),
    CONSTRAINT fk_venta_despacho FOREIGN KEY (id_venta) REFERENCES Ventas(id_venta) ON DELETE CASCADE
);

-- Creación de las tablas intermedias

CREATE TABLE PromocionAfiliados (
    id_afiliado NUMBER NOT NULL,  -- FK a Afiliados
    id_promocion NUMBER NOT NULL,  -- FK a Promociones
    fecha_inicio DATE,
    fecha_fin DATE,
    CONSTRAINT pk_promocion_afiliados PRIMARY KEY (id_afiliado, id_promocion),
    CONSTRAINT fk_afiliado_promocion FOREIGN KEY (id_afiliado) REFERENCES Afiliados(id_afiliado) ON DELETE CASCADE,
    CONSTRAINT fk_promocion FOREIGN KEY (id_promocion) REFERENCES Promociones(id_promocion) ON DELETE CASCADE
);

CREATE TABLE DetalleVenta (
    id_venta NUMBER NOT NULL,  -- FK a Ventas
    id_producto NUMBER NOT NULL,  -- FK a Productos
    cantidad NUMBER NOT NULL,
    precio_unitario NUMBER(10, 2) NOT NULL,
    CONSTRAINT pk_detalle_venta PRIMARY KEY (id_venta, id_producto),
    CONSTRAINT fk_venta_detalle FOREIGN KEY (id_venta) REFERENCES Ventas(id_venta) ON DELETE CASCADE,
    CONSTRAINT fk_producto_detalle FOREIGN KEY (id_producto) REFERENCES Productos(id_producto) ON DELETE CASCADE
);

CREATE TABLE DespachoProducto (
    id_despacho NUMBER NOT NULL,  -- FK a Despachos
    id_producto NUMBER NOT NULL,  -- FK a Productos
    cantidad_despachada NUMBER NOT NULL,
    CONSTRAINT pk_despacho_producto PRIMARY KEY (id_despacho, id_producto),
    CONSTRAINT fk_despacho FOREIGN KEY (id_despacho) REFERENCES Despachos(id_despacho) ON DELETE CASCADE,
    CONSTRAINT fk_producto_despacho FOREIGN KEY (id_producto) REFERENCES Productos(id_producto) ON DELETE CASCADE
);

CREATE TABLE AfiliadoComisiones (
    id_afiliado_comisionado NUMBER NOT NULL,  -- FK a Afiliados
    id_venta NUMBER NOT NULL,  -- FK a Ventas
    nivel NUMBER NOT NULL,
    monto_comision NUMBER(10, 2) NOT NULL,
    CONSTRAINT pk_afiliado_comisiones PRIMARY KEY (id_afiliado_comisionado, id_venta),
    CONSTRAINT fk_afiliado_comisionado FOREIGN KEY (id_afiliado_comisionado) REFERENCES Afiliados(id_afiliado) ON DELETE CASCADE,
    CONSTRAINT fk_venta_comision FOREIGN KEY (id_venta) REFERENCES Ventas(id_venta) ON DELETE CASCADE
);

CREATE INDEX idx_afiliados_nivel ON Afiliados(nivel);
CREATE INDEX idx_productos_stock ON Productos(stock);
CREATE INDEX idx_afiliados_id_superior ON Afiliados(id_afiliado_superior);

--Creación tablespaces
CREATE TABLESPACE TS_AFILIADOS
DATAFILE '/tmp/afiliados.dbf'
SIZE 20M
AUTOEXTEND ON NEXT 5M MAXSIZE 100M;
ALTER TABLE AFILIADOS MOVE TABLESPACE TS_AFILIADOS;
ALTER TABLE AFILIADOCOMISIONES MOVE TABLESPACE TS_AFILIADOS;

CREATE TABLESPACE TS_VENTAS
DATAFILE '/tmp/ventas.dbf'
SIZE 10M
AUTOEXTEND ON NEXT 5M MAXSIZE 50M;
ALTER TABLE VENTAS MOVE TABLESPACE TS_VENTAS;
ALTER TABLE DETALLEVENTA MOVE TABLESPACE TS_VENTAS;

CREATE TABLESPACE TS_PRODUCTOS
DATAFILE '/tmp/productos.dbf'
SIZE 10M
AUTOEXTEND ON NEXT 5M MAXSIZE 50M;
ALTER TABLE PRODUCTOS MOVE TABLESPACE TS_PRODUCTOS;

CREATE TABLESPACE TS_DESPACHOS
DATAFILE '/tmp/despachos.dbf'
SIZE 20M
AUTOEXTEND ON NEXT 5M MAXSIZE 100M;
ALTER TABLE DESPACHOS MOVE TABLESPACE TS_DESPACHOS;
ALTER TABLE DESPACHOPRODUCTO MOVE TABLESPACE TS_DESPACHOS;

CREATE TABLESPACE TS_PROMOCIONES
DATAFILE '/tmp/promociones.dbf'
SIZE 10M
AUTOEXTEND ON NEXT 5M MAXSIZE 50M;
ALTER TABLE PROMOCIONES MOVE TABLESPACE TS_PROMOCIONES;
ALTER TABLE PROMOCIONAFILIADOS MOVE TABLESPACE TS_PROMOCIONES;



